name: justdo-be

services:
  backend:
    build:
      context: ./just-do-backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '3000:3000'
    networks:
      - db_network
    depends_on:
      - database
      - fe_network
    volumes:
      - ./src:/app/src

  frontend:
    build:
      context: ./just-do-frontend
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - '4000:80'
    networks:
      - fe_network
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: justdo_be
      POSTGRES_PASSWORD: justbl00dyd01t
      POSTGRES_DB: justdo
    ports:
      - '5432:5432'
    networks:
      - db_network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - db_network
    depends_on:
      - database

volumes:
  db_data:

networks:
  db_network:
  fe_network:
