name: justdo-be

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    networks:
      - db_network
    depends_on:
      - database
    volumes:
      - nodemodules:/app/node_modules
      - ./src:/app/src

  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: justdo_be
      POSTGRES_PASSWORD: justbl00dyd01t
      POSTGRES_DB: justdo
    ports:
      - '5432:5432'
    networks:
      - db_network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - db_network
    depends_on:
      - database

volumes:
  db_data:
  nodemodules:

networks:
  db_network:
