
FROM node:20-alpine

LABEL mainteiner="Patrick Lima<patrickm.lima1@gmail.com>"

WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]