FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build -- --output-path=./dist/out --configuration production


FROM nginx:1.25.5-alpine

COPY --from=build /app/dist/out/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]